/*
 * generated by Xtext
 */
package fr.inria.lang.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import fr.inria.lang.ui.internal.VMActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class VMExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return VMActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return VMActivator.getInstance().getInjector(VMActivator.FR_INRIA_LANG_VM);
	}
	
}
