/*
 * generated by Xtext
 */
package fr.inria.lang.ui.contentassist

import fr.inria.lang.ui.contentassist.AbstractVMProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class VMProposalProvider extends AbstractVMProposalProvider {
}
