/*
 * generated by Xtext
 */
package fr.inria.lang.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class VMUiModule extends fr.inria.lang.ui.AbstractVMUiModule {
	public VMUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
