/*
* generated by Xtext
*/
package fr.inria.lang;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class VMStandaloneSetup extends VMStandaloneSetupGenerated{

	public static void doSetup() {
		new VMStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

